export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGING_OUT = 'USER_LOGGING_OUT';

export const GETTING_NOTIFICATIONS = 'GETTING_NOTIFICATIONS';
export const NOTIFICATIONS_RECEIVED = 'NOTIFICATIONS_RECEIVED';
export const GETTING_MESSAGES = 'GETTING_MESSAGES';
export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
